package:
  name: percolator
  version: '3.0'

source:
  git_url: https://github.com/percolator/percolator.git
  git_rev: c8a48c4 

build:
  number: 0


requirements:
  build:
    - cmake
    - gcc
    - zlib
    - boost
    - bzip2
  run:
    - gcc
    - zlib
    - boost
    - sqlite
    - bzip2


test:
  commands:
    - percolator --help 2>&1 > /dev/null | grep "Percolator version 3.00"

about:
  home: https://github.com/percolator/percolator
  license: Apache 2.0
  summary: Semi-supervised learning for peptide identification from shotgun proteomics datasets
