package:
  name: vsearch
  version: "2.2.0"

source:
  fn: v2.2.0.tar.gz
  url: https://github.com/torognes/vsearch/archive/v2.2.0.tar.gz
  md5: 255e567f6647a1e97bc6ebe83954f5d2

build:
  number: 1

requirements:
  build:
    - automake
    - autoconf
    - m4
    - gcc  # [linux]
    - llvm
  run:
    - libgcc  # [linux]

test:
  commands:
    - vsearch --version > /dev/null

about:
  home: https://github.com/torognes/vsearch
  license: "dual-licensed under GPLv3+ or BSD 2-clause"
  summary: "a versatile open source tool for metagenomics (USEARCH alternative)"
